# Generated by Django 4.2.7 on 2023-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quizzes_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
