# Generated by Django 4.2.7 on 2023-11-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_remove_quizzes_difficulty_questions_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
