# Generated by Django 4.2.7 on 2023-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_alter_userresponse_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
