# Generated by Django 4.2.7 on 2023-12-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_alter_questions_question_alter_questions_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='time_limit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
