# Generated by Django 4.2.7 on 2023-12-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_alter_quizzes_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizzes'),
        ),
    ]
