# Generated by Django 4.2.7 on 2024-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_remove_quizzes_duration_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
