# Generated by Django 4.2.7 on 2024-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0019_quizsession_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
